### PR TITLE
Rework the CMake-based build and add debian dir for packaging on Debian

### PR DESCRIPTION
**Pull request by lopippo**
Greetings, Fellow Developers,

this pull request is aimed to perform the installment of the CMake-based build system.

The modifications that I performed there (one single CMakeLists.txt file existed already) are aimed at allowing:
- to choose the install directory with cmake -DCMAKE_INSTALL_PREFIX=/usr, for example;
- to configure various toolchains for various GNU-based or Clang-based platforms (MinGW / MacOSX);
- to make it easy to add new toolchains for MSVC or XCode, for example;
- to package the project for Debian. The debian dir, which is non-intrusive, but that builds upon the CMake-build system, allows the immediate packaging of the project for Debian.

Of course, the integration of the debian/ dir is totally independent of the CMake-based build system. I just find it comfortable to have it "upstream", as we say, for my packaging of IsoSpec in Debian. I would understand perfectly that you keep that directory out of your scope :-)

To test that setup, just do something as the following:

cd <isospec_dev_dir>
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=./ ../

Nothing changes with respect to earlier builds, unless if you do

make install, in which case the lib will be installed in ./lib.

I hope you'll find this work useful and that we'll go on with CMake-based build system.

I will certainly create other pull requests in the future, when I will start porting IsoSpec to the other platforms.

Cheers,
Filippo

### CODE REVIEW

**Comment by michalsta** [comment]
Hi, few comments:

There are some .swp files in the PR, I'd guess they are editor's swap files and unneeded, can you confirm and remove if so?

Also, this is for the version 2.0. I'll be happy to pull it in of course, but you should know that right now we are not planning any new releases from that branch, even if bugs are found. Unless we do find someone affected by a bug AND unable to just go over to 2.1... The new API is mostly (though not *exactly*) a superset, so I hope there's going to be little trouble with that.

Also, please be aware that we didn't do ANY testing on non-x86 architectures. I'm not opposed to letting people try it and seeing what happens, and we will definitely try to help if there are any issues, but I dunno what are Debian's policies on having users beta-test stuff ;)

Otherwise, great work, thanks :)

**Comment by lopippo** [comment]
Greetings,

On Sat, Jun 06, 2020 at 07:00:00AM -0700, Michał Startek wrote:
>
>There are some .swp files in the PR, I'd guess they are editor's swap files and unneeded, can you confirm and remove if so?

Oh, yes, I'll remove them and clean before I request a new pull.
>
>Also, this is for the version 2.0. I'll be happy to pull it in of course, but you should know that right now we are not planning any new releases from that branch, even if bugs are found. Unless we do find someone affected by a bug AND unable to just go over to 2.1... The new API is mostly (though not *exactly*) a superset, so I hope there's going to be little trouble with that.

That is the default branch in GitHub. I'll check 2.1, then before requesting for
a pull. 

>Also, please be aware that we didn't do ANY testing on non-x86 architectures. I'm not opposed to letting people try it and seeing what happens, and we will definitely try to help if there are any issues, but I dunno what are Debian's policies on having users beta-test stuff ;)

Well, this is not system software. And in my hand seems pretty stable (amd64).
So I guess this is fine.

>Otherwise, great work, thanks :)

Thanks, I'll let you know then.

Cheers,
Filippo

-- 

⢀⣴⠾⠻⢶⣦⠀  Filippo Rusconi, PhD
⣾⠁⢠⠒⠀⣿⡁   Research scientist at CNRS
⢿⡄⠘⠷⠚⠋⠀   Debian Developer
⠈⠳⣄⠀⠀⠀⠀  http://msxpertsuite.org
           http://www.debian.org

**Comment by michalsta** [comment]
Yeah, version_2_1 is the default since about a week ago ;) probably switched after you already started working...

Also, by "x86" i meant the 32 and 64 bit variants. Those we did test, I the "untested" comment refers to all the "weird" architectures Debian is ported to, like alpha, MIPS and so on...

**Comment by lopippo** [comment]
I could not understand how to create a new branch in my fork repos of isospec... I deleted the project and forked it anew. Forget about the previous pull request. A new one against branch version_2_1 will be sent soon.

Cheers,
Filippo

**Comment by michalsta** [comment]
Closing obsolete pull request, superseded by 3576fb5e35a8334849985765a7e5097686318f11

**Pull request closed without merging**
