### PR TITLE
New raft of modifs

### PR DESCRIPTION
**Pull request by lopippo**
Greetings,

the new modifications that I suggest here:

- remove the debian patches that used to implement the CMake-based build system
  since now that system will eventually end up in upstream;
- automate the generation of the logo graphics file with the proper version;
- automate the production of the Doxygen-based doc with the proper version;
- add custom target 'make doc' to produce the Doxygen-based documentation;

Since none of all the modifications did touch the core code of the libs ever, I would be glad if you could  create a minor revision, say 2_1_1, for example, with all these last modifs in, so that I could create a new version of the Debian package and send that to the repositories (I need an upstream tarball with that revision number).

In the hope you find these modifs acceptable,

Cheers, Filippo

### CODE REVIEW

**Comment by michalsta** [comment]
Right. We are getting ready for a 2.1.1 with some speed improvements, I'll pull also the build system improvements when we get these sorted in a few days.

**Comment by lopippo** [comment]
Great,
thank you so much.
Filippo

**Comment by lopippo** [comment]
Some more development, this evening, with improvements to the documentation handling.
Cheers,
Filippo

**Comment by michalsta** [comment]
Hi, just an update: we should be ready to release 2.1.1 in about two weeks from now (basically we still want to so few performance tweaks, and wait for an aleady accepted paper about 2.0 to finally get published, so we can update the citation info), we will add the build system in that release. Then you could package it for Debian. Is that okay?

**Comment by lopippo** [comment]
Greetings, Matteo,

On Sat, Jun 20, 2020 at 08:39:00AM -0700, Michał Startek wrote:
>Hi, just an update: we should be ready to release 2.1.1 in about two weeks from now (basically we still want to so few performance tweaks, and wait for an aleady accepted paper about 2.0 to finally get published, so we can update the citation info), we will add the build system in that release. Then you could package it for Debian. Is that okay?
>
Congratulations for your article !

Yes, that would be fine. Tell me when I should download the new 2.1.1 version
and I'll confirm the packaging is OK with it.

Thank you,

Ciao
Filippo

-- 

⢀⣴⠾⠻⢶⣦⠀  Filippo Rusconi, PhD
⣾⠁⢠⠒⠀⣿⡁   Research scientist at CNRS
⢿⡄⠘⠷⠚⠋⠀   Debian Developer
⠈⠳⣄⠀⠀⠀⠀  http://msxpertsuite.org
           http://www.debian.org

**Comment by MatteoLacki** [comment]
That there was Michał not me :)
The article is indeed nice to have :)

Cheerio!

*Mateusz Krzysztof Łącki*

*German tel. +49 159 01681376*
Polish tel. +48 579 647 311
Skype:   mathewin
GitHub: MatteoLacki <https://github.com/MatteoLacki>

**Comment by michalsta** [comment]
Hi

2.1.1 is out, we're ready for packaging, it's merge time :)

**Comment by lopippo** [comment]
Greetings, Michal and Matteo,

On Wed, Jul 08, 2020 at 02:31:41AM -0700, Michał Startek wrote:
>
>2.1.1 is out, we're ready for packaging, it's merge time :)

That is very good ! I'll make a pull as soon as possible and see how I get to
have a Debian package, then compile my progs against it and check everything is
fine. I may have to tweak some things. Then we'll have a firm basis for going on!

Again, thanks for making IsoSpec Free Software. Yesterday I was giving a seminar
about it and its integration in mineXpert2.

Cheers,
Filippo

-- 

⢀⣴⠾⠻⢶⣦⠀  Filippo Rusconi, PhD
⣾⠁⢠⠒⠀⣿⡁   Research scientist at CNRS
⢿⡄⠘⠷⠚⠋⠀   Debian Developer
⠈⠳⣄⠀⠀⠀⠀  http://msxpertsuite.org
           http://www.debian.org

**Pull request merged**
